# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_profile_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_information', models.TextField()),
            ],
        ),
    ]
