# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0006_auto_20170704_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ip_address',
        ),
    ]
