# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_historicalprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestinformation',
            name='http_information',
        ),
        migrations.AddField(
            model_name='requestinformation',
            name='execution_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='requestinformation',
            name='request_method',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
