# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0009_auto_20170705_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinformation',
            name='execution_time',
            field=models.DateTimeField(),
        ),
    ]
