# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0014_auto_20170706_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
